# Import the libraries

In [1]:
import numpy as np
import pandas as pd
import tensorflow as tf

# Load the dataset

In [2]:
data=pd.read_csv('D:/CapStone Project/Dumb/Models/Heart Dataset/heart.csv')

In [3]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1025 entries, 0 to 1024
Data columns (total 14 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   age       1025 non-null   int64  
 1   sex       1025 non-null   int64  
 2   cp        1025 non-null   int64  
 3   trestbps  1025 non-null   int64  
 4   chol      1025 non-null   int64  
 5   fbs       1025 non-null   int64  
 6   restecg   1025 non-null   int64  
 7   thalach   1025 non-null   int64  
 8   exang     1025 non-null   int64  
 9   oldpeak   1025 non-null   float64
 10  slope     1025 non-null   int64  
 11  ca        1025 non-null   int64  
 12  thal      1025 non-null   int64  
 13  target    1025 non-null   int64  
dtypes: float64(1), int64(13)
memory usage: 112.2 KB


In [4]:
data.describe()

age          sex           cp     trestbps        chol  \
count  1025.000000  1025.000000  1025.000000  1025.000000  1025.00000   
mean     54.434146     0.695610     0.942439   131.611707   246.00000   
std       9.072290     0.460373     1.029641    17.516718    51.59251   
min      29.000000     0.000000     0.000000    94.000000   126.00000   
25%      48.000000     0.000000     0.000000   120.000000   211.00000   
50%      56.000000     1.000000     1.000000   130.000000   240.00000   
75%      61.000000     1.000000     2.000000   140.000000   275.00000   
max      77.000000     1.000000     3.000000   200.000000   564.00000   

               fbs      restecg      thalach        exang      oldpeak  \
count  1025.000000  1025.000000  1025.000000  1025.000000  1025.000000   
mean      0.149268     0.529756   149.114146     0.336585     1.071512   
std       0.356527     0.527878    23.005724     0.472772     1.175053   
min       0.000000     0.000000    71.000000     0.000000     0.000000   
25%       0.000000     0.000000   132.000000     0.000000     0.000000   
50%       0.000000     1.000000   152.000000     0.000000     0.800000   
75%       0.000000     1.000000   166.000000     1.000000     1.800000   
max       1.000000     2.000000   202.000000     1.000000     6.200000   

             slope           ca         thal       target  
count  1025.000000  1025.000000  1025.000000  1025.000000  
mean      1.385366     0.754146     2.323902     0.513171  
std       0.617755     1.030798     0.620660     0.500070  
min       0.000000     0.000000     0.000000     0.000000  
25%       1.000000     0.000000     2.000000     0.000000  
50%       1.000000     0.000000     2.000000     1.000000  
75%       2.000000     1.000000     3.000000     1.000000  
max       2.000000     4.000000     3.000000     1.000000

In [5]:
data.head()

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  slope  \
0   52    1   0       125   212    0        1      168      0      1.0      2   
1   53    1   0       140   203    1        0      155      1      3.1      0   
2   70    1   0       145   174    0        1      125      1      2.6      0   
3   61    1   0       148   203    0        1      161      0      0.0      2   
4   62    0   0       138   294    1        1      106      0      1.9      1   

   ca  thal  target  
0   2     3       0  
1   0     3       0  
2   0     3       0  
3   1     3       0  
4   3     2       0

In [6]:
data.isnull().sum()

age         0
sex         0
cp          0
trestbps    0
chol        0
fbs         0
restecg     0
thalach     0
exang       0
oldpeak     0
slope       0
ca          0
thal        0
target      0
dtype: int64

In [7]:
data["target"].value_counts()

1    526
0    499
Name: target, dtype: int64

# Slice the dataset

In [8]:
x=data.iloc[:,:-1].values
y=data.iloc[:,-1].values

In [9]:
x

array([[52.,  1.,  0., ...,  2.,  2.,  3.],
       [53.,  1.,  0., ...,  0.,  0.,  3.],
       [70.,  1.,  0., ...,  0.,  0.,  3.],
       ...,
       [47.,  1.,  0., ...,  1.,  1.,  2.],
       [50.,  0.,  0., ...,  2.,  0.,  2.],
       [54.,  1.,  0., ...,  1.,  1.,  3.]])

In [10]:
y

array([0, 0, 0, ..., 0, 1, 0], dtype=int64)

# Imbalancing technique

# Over_sampling technique

In [11]:
from imblearn.over_sampling import RandomOverSampler
ro=RandomOverSampler()
x_data,y_data=ro.fit_resample(x,y)
from collections import Counter
print("Actual Data:",Counter(y))
print("Artificial Data:",Counter(y_data))

Actual Data: Counter({1: 526, 0: 499})
Artificial Data: Counter({0: 526, 1: 526})


# Slice the dataset into training set and testing test

In [12]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=0)

# Standardscaler

In [13]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
x_train=sc.fit_transform(x_train)
x_test=sc.transform(x_test)
x_train

array([[-1.40503359,  0.64895597,  1.97748631, ...,  0.97028605,
         1.17427458, -0.5144228 ],
       [ 1.26270023, -1.5409366 ,  1.01170979, ..., -0.6668221 ,
         0.21616   , -0.5144228 ],
       [-0.18232226,  0.64895597,  1.01170979, ...,  0.97028605,
         2.13238916, -0.5144228 ],
       ...,
       [ 1.15154465,  0.64895597,  1.97748631, ..., -0.6668221 ,
         0.21616   , -0.5144228 ],
       [ 1.3738558 ,  0.64895597, -0.91984324, ..., -0.6668221 ,
        -0.74195458, -0.5144228 ],
       [ 0.59576677,  0.64895597,  1.01170979, ..., -0.6668221 ,
        -0.74195458, -0.5144228 ]])

In [14]:
np.var(x_train)

1.000000000000001

# Building the ANN

In [15]:
ann=tf.keras.models.Sequential()

# Adding the input layer and the first hidden layer

In [16]:
ann.add(tf.keras.layers.Dense(units=6,activation="relu"))

# Adding the second hidden layer

In [17]:
ann.add(tf.keras.layers.Dense(units=6,activation="relu"))

# Adding the output layer

In [18]:
ann.add(tf.keras.layers.Dense(units=1,activation="sigmoid"))

# Training the ANN

In [19]:
ann.compile(optimizer="adam",loss="binary_crossentropy",metrics=["accuracy"])

# Training the ANN on the Training set

In [20]:
ann.fit(x_train,y_train,batch_size=32,epochs=100)

Epoch 1/100
26/26 [==============================] - 1s 2ms/step - loss: 0.8037 - accuracy: 0.4122
Epoch 2/100
26/26 [==============================] - 0s 2ms/step - loss: 0.7287 - accuracy: 0.5159
Epoch 3/100
26/26 [==============================] - 0s 1ms/step - loss: 0.6740 - accuracy: 0.5915
Epoch 4/100
26/26 [==============================] - 0s 1ms/step - loss: 0.6325 - accuracy: 0.6585
Epoch 5/100
26/26 [==============================] - 0s 2ms/step - loss: 0.6004 - accuracy: 0.7073
Epoch 6/100
26/26 [==============================] - 0s 2ms/step - loss: 0.5709 - accuracy: 0.7280
Epoch 7/100
26/26 [==============================] - 0s 2ms/step - loss: 0.5436 - accuracy: 0.7427
Epoch 8/100
26/26 [==============================] - 0s 2ms/step - loss: 0.5175 - accuracy: 0.7439
Epoch 9/100
26/26 [==============================] - 0s 2ms/step - loss: 0.4927 - accuracy: 0.7524
Epoch 10/100
26/26 [==============================] - 0s 2ms/step - loss: 0.4700 - accuracy: 0.7732
Epoch 11/

# Predicting the Test set results

In [21]:
y_pred=ann.predict(x_test)
y_pred=(y_pred>0.5)
print(np.concatenate((y_pred.reshape(len(y_pred),1),y_test.reshape(len(y_test),1)),1))

7/7 [==============================] - 0s 2ms/step
[[1 1]
 [1 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [1 1]
 [1 1]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [0 0]
 [1 1]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [1 0]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [1 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [1 0]
 [1 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [1 0]
 [0 1]
 [0 0]
 [0 0]
 [0 0]
 [1 0]
 [1 1]
 [1 0]
 [1 1]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [1 1]
 [1 0]
 [0 1]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [1 0]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [1 1]
 [0 

# Making the Confusion Matrix

In [22]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print("",cm)

 [[ 86  12]
 [  5 102]]


In [23]:
acc=accuracy_score(y_test, y_pred)*100
print("Accuracy of ANN model is :",acc) 

Accuracy of ANN model is : 91.70731707317074


In [24]:
from sklearn.metrics import classification_report
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.95      0.88      0.91        98
           1       0.89      0.95      0.92       107

    accuracy                           0.92       205
   macro avg       0.92      0.92      0.92       205
weighted avg       0.92      0.92      0.92       205

